name: city
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  either_dart: ^1.0.0
  dio: ^5.7.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
